apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitboy-backend
  namespace: rabbitboy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitboy-backend
  template:
    metadata:
      labels:
        app: rabbitboy-backend
    spec:
      containers:
        - name: backend
          image: rabbitboy0134/rabbitboy-backend:sha-683d7a82a013db7b94bd2568bed2d33bd18565e4
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
